# Generated by Django 5.2 on 2025-06-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_user_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Role',
            field=models.IntegerField(choices=[(0, 'Restaurant'), (1, 'Customer'), (2, 'Administrator')], default=1),
        ),
    ]
