# Generated by Django 5.2 on 2025-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_user_details_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='cover_picture',
            field=models.ImageField(blank=True, default='cover_pictures/default.png', null=True, upload_to='cover_pictures/'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
