# Generated by Django 5.2 on 2025-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_user_details_cover_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='cover_picture',
            field=models.ImageField(default='cover_pictures/default.png', upload_to='cover_pictures/'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
